version: '3'

volumes:
  pg_data_prod:
  static_prod:
  media_prod:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
  backend:
    image: salavatakhiyarov/kittygram_backend
    env_file: .env
    volumes:
      - static_prod:/backend_static
      - media_prod:/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: salavatakhiyarov/kittygram_frontend
    command: sh -c "cp -r /app/build/. /static/ && echo 'Build copied'"
    volumes:
      - static_prod:/static
  gateway:
    image: salavatakhiyarov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static_prod:/static
      - media_prod:/app/media
    depends_on:
      - backend
      - frontend